apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "dev"
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/jstrachan/jx3-demo-catalog-dev.git
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: "Never"
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    buildPackRef: "master"
    buildPackUrl: "https://github.com/jenkins-x/jx3-pipeline-catalog.git"
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: "jenkins-x-labs-bdd"
    envOrganisation: todo
    gitServer: https://github.com
    gitPublic: true
    helmTemplate: true
    kubeProvider: "gke"
    pipelineUsername: "jstrachan"
    pipelineUserEmail: "jenkins-x@googlegroups.com"
    prowConfig: Scheduler
    importMode: YAML
    promotionEngine: Prow
    prowEngine: Tekton
    versionStreamUrl: "https://github.com/jenkins-x/jxr-versions.git"
    versionStreamRef: "master"
    useGitOps: true
